// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: avmacwtxpcxkwzafdcda

class SupabaseConfig {
  static const String supabaseUrl = 'https://avmacwtxpcxkwzafdcda.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bWFjd3R4cGN4a3d6YWZkY2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTc4MzQsImV4cCI6MjA3MjI5MzgzNH0.WZ8FQGlA7rXxc2zUoEwXai4eEbhy6ckAs9DWt7oWIBI';
}
